var annotated_dup =
[
    [ "Building_System", "namespace_building___system.html", [
      [ "Place", "class_building___system_1_1_place.html", "class_building___system_1_1_place" ],
      [ "PlaceBlock", "class_building___system_1_1_place_block.html", "class_building___system_1_1_place_block" ],
      [ "Preview", "class_building___system_1_1_preview.html", "class_building___system_1_1_preview" ]
    ] ],
    [ "CB_Interfaces", "namespace_c_b___interfaces.html", [
      [ "IDialogue", "interface_c_b___interfaces_1_1_i_dialogue.html", "interface_c_b___interfaces_1_1_i_dialogue" ],
      [ "IGetItem", "interface_c_b___interfaces_1_1_i_get_item.html", "interface_c_b___interfaces_1_1_i_get_item" ],
      [ "ISave", "interface_c_b___interfaces_1_1_i_save.html", "interface_c_b___interfaces_1_1_i_save" ],
      [ "IUseItem", "interface_c_b___interfaces_1_1_i_use_item.html", "interface_c_b___interfaces_1_1_i_use_item" ],
      [ "IValidate", "interface_c_b___interfaces_1_1_i_validate.html", "interface_c_b___interfaces_1_1_i_validate" ]
    ] ],
    [ "CB_Puzzles", "namespace_c_b___puzzles.html", [
      [ "CheckActivator", "class_c_b___puzzles_1_1_check_activator.html", "class_c_b___puzzles_1_1_check_activator" ],
      [ "InteractButton", "class_c_b___puzzles_1_1_interact_button.html", "class_c_b___puzzles_1_1_interact_button" ],
      [ "TimedButton", "class_c_b___puzzles_1_1_timed_button.html", "class_c_b___puzzles_1_1_timed_button" ]
    ] ],
    [ "CB_Scanner", "namespace_c_b___scanner.html", [
      [ "Scan", "class_c_b___scanner_1_1_scan.html", "class_c_b___scanner_1_1_scan" ],
      [ "Scanable", "class_c_b___scanner_1_1_scanable.html", "class_c_b___scanner_1_1_scanable" ],
      [ "ScanedBuild", "class_c_b___scanner_1_1_scaned_build.html", "class_c_b___scanner_1_1_scaned_build" ]
    ] ],
    [ "Craft_System", "namespace_craft___system.html", [
      [ "CraftStation", "class_craft___system_1_1_craft_station.html", "class_craft___system_1_1_craft_station" ],
      [ "ItemVain", "class_craft___system_1_1_item_vain.html", "class_craft___system_1_1_item_vain" ],
      [ "LegacyCraftStation", "class_craft___system_1_1_legacy_craft_station.html", "class_craft___system_1_1_legacy_craft_station" ]
    ] ],
    [ "Inventory_System", "namespace_inventory___system.html", [
      [ "Inventory_UI", "namespace_inventory___system_1_1_inventory___u_i.html", [
        [ "DraggableComponent", "class_inventory___system_1_1_inventory___u_i_1_1_draggable_component.html", "class_inventory___system_1_1_inventory___u_i_1_1_draggable_component" ],
        [ "DropItemSlot", "class_inventory___system_1_1_inventory___u_i_1_1_drop_item_slot.html", "class_inventory___system_1_1_inventory___u_i_1_1_drop_item_slot" ],
        [ "MaterialManagerButton", "class_inventory___system_1_1_inventory___u_i_1_1_material_manager_button.html", "class_inventory___system_1_1_inventory___u_i_1_1_material_manager_button" ]
      ] ],
      [ "InventoryManager", "class_inventory___system_1_1_inventory_manager.html", "class_inventory___system_1_1_inventory_manager" ],
      [ "InventorySelector", "class_inventory___system_1_1_inventory_selector.html", "class_inventory___system_1_1_inventory_selector" ],
      [ "Item", "class_inventory___system_1_1_item.html", "class_inventory___system_1_1_item" ],
      [ "MaterialsManager", "class_inventory___system_1_1_materials_manager.html", "class_inventory___system_1_1_materials_manager" ]
    ] ],
    [ "Optimization_Module", "namespace_optimization___module.html", [
      [ "RadarVFC", "class_optimization___module_1_1_radar_v_f_c.html", "class_optimization___module_1_1_radar_v_f_c" ]
    ] ],
    [ "UnityTemplateProjects", "namespace_unity_template_projects.html", [
      [ "SimpleCameraController", "class_unity_template_projects_1_1_simple_camera_controller.html", "class_unity_template_projects_1_1_simple_camera_controller" ]
    ] ],
    [ "AnimationControl", "class_animation_control.html", "class_animation_control" ],
    [ "ApiManager", "class_api_manager.html", "class_api_manager" ],
    [ "AudioManager", "class_audio_manager.html", "class_audio_manager" ],
    [ "AuthenticationController", "class_authentication_controller.html", "class_authentication_controller" ],
    [ "AuthenticationRepository", "class_authentication_repository.html", "class_authentication_repository" ],
    [ "AuthenticationService", "class_authentication_service.html", "class_authentication_service" ],
    [ "BlockDTO", "class_block_d_t_o.html", "class_block_d_t_o" ],
    [ "BrickProperties", "class_brick_properties.html", "class_brick_properties" ],
    [ "Buoyancy", "class_buoyancy.html", "class_buoyancy" ],
    [ "ButtonAnimationController", "class_button_animation_controller.html", "class_button_animation_controller" ],
    [ "CatalogueRepository", "class_catalogue_repository.html", "class_catalogue_repository" ],
    [ "ChallengeDTO", "class_challenge_d_t_o.html", "class_challenge_d_t_o" ],
    [ "ChallengeResponse", "struct_challenge_response.html", "struct_challenge_response" ],
    [ "ChallengeSystem", "class_challenge_system.html", "class_challenge_system" ],
    [ "ChallengeTableViewCell", "class_challenge_table_view_cell.html", "class_challenge_table_view_cell" ],
    [ "ChangeText", "class_change_text.html", "class_change_text" ],
    [ "Character", "class_character.html", "class_character" ],
    [ "checkCollide", "classcheck_collide.html", "classcheck_collide" ],
    [ "CheckCollision", "class_check_collision.html", "class_check_collision" ],
    [ "Chest", "class_chest.html", "class_chest" ],
    [ "ColliderDetect", "class_collider_detect.html", null ],
    [ "CollisionCheckers", "class_collision_checkers.html", "class_collision_checkers" ],
    [ "ConnectionPoints", "class_connection_points.html", "class_connection_points" ],
    [ "Consume", "class_consume.html", "class_consume" ],
    [ "Conversation", "class_conversation.html", "class_conversation" ],
    [ "CorkHarvesting", "class_cork_harvesting.html", "class_cork_harvesting" ],
    [ "CraftManager", "class_craft_manager.html", "class_craft_manager" ],
    [ "CubePlacer", "class_cube_placer.html", "class_cube_placer" ],
    [ "DataManipulation", "class_data_manipulation.html", "class_data_manipulation" ],
    [ "DialogDisplay", "class_dialog_display.html", "class_dialog_display" ],
    [ "Dialogos", "struct_dialogos.html", "struct_dialogos" ],
    [ "DialogueTrigger", "class_dialogue_trigger.html", "class_dialogue_trigger" ],
    [ "Door", "class_door.html", "class_door" ],
    [ "FoodDrinkTemplate", "class_food_drink_template.html", "class_food_drink_template" ],
    [ "FreeCam", "class_free_cam.html", "class_free_cam" ],
    [ "GameManager", "class_game_manager.html", "class_game_manager" ],
    [ "GameSounds", "class_game_sounds.html", "class_game_sounds" ],
    [ "GlobalVariables", "class_global_variables.html", "class_global_variables" ],
    [ "Grid", "class_grid.html", "class_grid" ],
    [ "HiddenChestManager", "class_hidden_chest_manager.html", "class_hidden_chest_manager" ],
    [ "HiddenNotes", "class_hidden_notes.html", "class_hidden_notes" ],
    [ "HightLightInteractables", "class_hight_light_interactables.html", null ],
    [ "HungerSystem", "class_hunger_system.html", "class_hunger_system" ],
    [ "InputManager", "class_input_manager.html", "class_input_manager" ],
    [ "InputManagerConstruction", "class_input_manager_construction.html", "class_input_manager_construction" ],
    [ "InventorySelectionUI", "class_inventory_selection_u_i.html", "class_inventory_selection_u_i" ],
    [ "ItemPlacer", "class_item_placer.html", "class_item_placer" ],
    [ "ItemSlot", "class_item_slot.html", "class_item_slot" ],
    [ "ItemSlotData", "class_item_slot_data.html", "class_item_slot_data" ],
    [ "Line", "struct_line.html", "struct_line" ],
    [ "LoadFile", "class_load_file.html", null ],
    [ "Look", "class_look.html", "class_look" ],
    [ "LookTowardsPlayer", "class_look_towards_player.html", "class_look_towards_player" ],
    [ "Loot", "class_loot.html", "class_loot" ],
    [ "MainPlayer", "class_main_player.html", "class_main_player" ],
    [ "MainTableController", "class_main_table_controller.html", "class_main_table_controller" ],
    [ "ManagersInputsFromPlayer", "class_managers_inputs_from_player.html", null ],
    [ "MapControl", "class_map_control.html", "class_map_control" ],
    [ "Menu", "class_menu.html", "class_menu" ],
    [ "MeshCombiner", "class_mesh_combiner.html", null ],
    [ "ModelInfo", "struct_model_info.html", "struct_model_info" ],
    [ "Move", "class_move.html", "class_move" ],
    [ "NotesManager", "class_notes_manager.html", "class_notes_manager" ],
    [ "ObjectManipulation", "class_object_manipulation.html", "class_object_manipulation" ],
    [ "ObjectPlacer", "class_object_placer.html", "class_object_placer" ],
    [ "ObjectProperties", "class_object_properties.html", "class_object_properties" ],
    [ "ObjectScatter", "class_object_scatter.html", "class_object_scatter" ],
    [ "OrbitCamera", "class_orbit_camera.html", "class_orbit_camera" ],
    [ "ParrotHelpManager", "class_parrot_help_manager.html", null ],
    [ "PlaceablePrefarb", "struct_placeable_prefarb.html", "struct_placeable_prefarb" ],
    [ "PlacedBrocksData", "class_placed_brocks_data.html", "class_placed_brocks_data" ],
    [ "RayResult", "struct_ray_result.html", "struct_ray_result" ],
    [ "Recepi", "class_recepi.html", "class_recepi" ],
    [ "recepidata", "classrecepidata.html", "classrecepidata" ],
    [ "Recepies", "class_recepies.html", "class_recepies" ],
    [ "RenderObject", "class_render_object.html", "class_render_object" ],
    [ "SavedObject", "class_saved_object.html", "class_saved_object" ],
    [ "SavedPlayer", "class_saved_player.html", "class_saved_player" ],
    [ "SaveSystem", "class_save_system.html", "class_save_system" ],
    [ "SceneLoader", "class_scene_loader.html", "class_scene_loader" ],
    [ "SceneM", "class_scene_m.html", "class_scene_m" ],
    [ "Settings", "class_settings.html", "class_settings" ],
    [ "SettingsMan", "class_settings_man.html", null ],
    [ "Solution", "class_solution.html", "class_solution" ],
    [ "SpeakerUI", "class_speaker_u_i.html", "class_speaker_u_i" ],
    [ "StartStory", "class_start_story.html", null ],
    [ "StoryBoardControl", "class_story_board_control.html", "class_story_board_control" ],
    [ "StringIntEditorDictionary", "class_string_int_editor_dictionary.html", "class_string_int_editor_dictionary" ],
    [ "ThirstSystem", "class_thirst_system.html", "class_thirst_system" ],
    [ "timeMan", "classtime_man.html", "classtime_man" ],
    [ "ToggleGameObjectEnable", "class_toggle_game_object_enable.html", null ],
    [ "UI_Manager", "class_u_i___manager.html", "class_u_i___manager" ],
    [ "UIController", "class_u_i_controller.html", null ],
    [ "underwater", "classunderwater.html", null ],
    [ "UndoAction", "struct_undo_action.html", "struct_undo_action" ],
    [ "UseSelectedItem", "class_use_selected_item.html", "class_use_selected_item" ],
    [ "WaterBody", "class_water_body.html", "class_water_body" ],
    [ "weatherObj", "structweather_obj.html", "structweather_obj" ],
    [ "WeatherUpdate", "class_weather_update.html", "class_weather_update" ]
];